### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [96]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [97]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[63, 60, 76, 88],
       [60, 68, 60, 99],
       [76, 55, 50, 68],
       [14, 53, 72, 75],
       [83, 54, 24, 97],
       [80, 64, 11, 13]])

In [98]:
np.sort(a)[::-1]

array([99, 88, 83, 83, 82, 76, 68, 64, 48, 44, 34, 24, 19, 14,  1])

In [99]:
np.sort(b,axis=0)

array([[14, 53, 11, 13],
       [60, 54, 24, 68],
       [63, 55, 50, 75],
       [76, 60, 60, 88],
       [80, 64, 72, 97],
       [83, 68, 76, 99]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [100]:
# code
np.append(a,200)

array([ 83,  48,  83,  24,  19,  82,   1,  76,  88,  34,  44,  68,  14,
        99,  64, 200])

In [101]:
b

array([[63, 60, 76, 88],
       [60, 68, 60, 99],
       [76, 55, 50, 68],
       [14, 53, 72, 75],
       [83, 54, 24, 97],
       [80, 64, 11, 13]])

In [102]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[63.        , 60.        , 76.        , 88.        ,  0.57090704],
       [60.        , 68.        , 60.        , 99.        ,  0.21422799],
       [76.        , 55.        , 50.        , 68.        ,  0.45571271],
       [14.        , 53.        , 72.        , 75.        ,  0.85074305],
       [83.        , 54.        , 24.        , 97.        ,  0.228818  ],
       [80.        , 64.        , 11.        , 13.        ,  0.21984698]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [103]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [104]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [105]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [106]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [107]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [108]:
# code
a.shape

(15,)

In [109]:
np.expand_dims(a,axis=0)

array([[83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64]])

In [110]:
np.expand_dims(a,axis=1)

array([[83],
       [48],
       [83],
       [24],
       [19],
       [82],
       [ 1],
       [76],
       [88],
       [34],
       [44],
       [68],
       [14],
       [99],
       [64]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [111]:
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [112]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  5,  7,  8, 11, 13, 14]),)

In [113]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 48,  0, 24, 19,  0,  1,  0,  0, 34, 44,  0, 14,  0,  0])

In [114]:
np.where(a % 2 == 0,0,a)

array([83,  0, 83,  0, 19,  0,  1,  0,  0,  0,  0,  0,  0, 99,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [115]:
# code
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [116]:
np.argmax(a)

np.int64(13)

In [117]:
b

array([[63, 60, 76, 88],
       [60, 68, 60, 99],
       [76, 55, 50, 68],
       [14, 53, 72, 75],
       [83, 54, 24, 97],
       [80, 64, 11, 13]])

In [118]:
np.argmax(b,axis=0)

array([4, 1, 0, 1])

In [119]:
np.argmax(b,axis=1)

array([3, 3, 0, 3, 3, 0])

In [120]:
# np.argmin
np.argmin(b,axis=1)

array([1, 0, 2, 0, 2, 2])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [121]:
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [122]:
np.cumsum(a)

array([ 83, 131, 214, 238, 257, 339, 340, 416, 504, 538, 582, 650, 664,
       763, 827])

In [123]:
b

array([[63, 60, 76, 88],
       [60, 68, 60, 99],
       [76, 55, 50, 68],
       [14, 53, 72, 75],
       [83, 54, 24, 97],
       [80, 64, 11, 13]])

In [124]:
np.cumsum(b)

array([  63,  123,  199,  287,  347,  415,  475,  574,  650,  705,  755,
        823,  837,  890,  962, 1037, 1120, 1174, 1198, 1295, 1375, 1439,
       1450, 1463])

In [125]:
np.cumsum(b,axis=1)

array([[ 63, 123, 199, 287],
       [ 60, 128, 188, 287],
       [ 76, 131, 181, 249],
       [ 14,  67, 139, 214],
       [ 83, 137, 161, 258],
       [ 80, 144, 155, 168]])

In [126]:
# np.cumprod
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [127]:
np.cumprod(a)

array([                  83,                 3984,               330672,
                    7936128,            150786432,          12364487424,
                12364487424,         939701044224,       82693691891712,
           2811585524318208,   123709763070001152,  8412263888760078336,
        7091230000383787008,  1055495237031952384, -6235281124793253888])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [128]:
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [129]:
np.percentile(a,100)

np.float64(99.0)

In [130]:
np.percentile(a,50)

np.float64(64.0)

In [131]:
np.median(a)

np.float64(64.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [132]:
# code
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [133]:
np.sort(a)

array([ 1, 14, 19, 24, 34, 44, 48, 64, 68, 76, 82, 83, 83, 88, 99])

In [134]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [135]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [136]:
# code
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [137]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([], dtype=int64)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [138]:
# code
a

array([83, 48, 83, 24, 19, 82,  1, 76, 88, 34, 44, 68, 14, 99, 64])

In [139]:
np.flip(a)

array([64, 99, 14, 68, 44, 34, 88, 76,  1, 82, 19, 24, 83, 48, 83])

In [140]:
b

array([[63, 60, 76, 88],
       [60, 68, 60, 99],
       [76, 55, 50, 68],
       [14, 53, 72, 75],
       [83, 54, 24, 97],
       [80, 64, 11, 13]])

In [161]:
np.flip(b,axis=0)

array([[80, 64, 11, 13],
       [83, 54, 24, 97],
       [14, 53, 72, 75],
       [76, 55, 50, 68],
       [60, 68, 60, 99],
       [63, 60, 76, 88]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [169]:
# code
a

array([110, 530,  83,  24,  19,  82,   1,  76,  88,  34,  44,  68,  14,
       550, 222])

In [168]:
np.put(a,[-1,-2],[222,550])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [170]:
# code
a

array([110, 530,  83,  24,  19,  82,   1,  76,  88,  34,  44,  68,  14,
       550, 222])

In [171]:
np.delete(a,[0,1])

array([ 83,  24,  19,  82,   1,  76,  88,  34,  44,  68,  14, 550, 222])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d

In [173]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
m

array([1, 2, 3, 4, 5])

In [177]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [178]:
np.intersect1d(m,n)

array([3, 4, 5])

In [181]:
np.setdiff1d(m,n)

array([1, 2])

In [182]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [189]:
# code
a

array([110, 530,  83,  24,  19,  82,   1,  76,  88,  34,  44,  68,  14,
       550, 222])

In [190]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 25, 75, 25, 75, 75, 34, 44, 68, 25, 75, 75])