In [26]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

🟢 Task 1: Fancy Indexing
---

From arr, extract elements at indices:

      0, 2, 4

Print the result.

In [3]:
print("Extract Elements From Perticular Indices : ",arr[[0,2,4]])

Extract Elements From Perticular Indices :  [10 30 50]


🟢 Task 2: Conditional Selection
---

From arr, extract only values greater than 25.

Print the result.

In [4]:
print("Greater Than 25 Values are : ", arr[arr > 25])

Greater Than 25 Values are :  [30 40 50]


🟢 Task 3: Sorting (1D)
---

 Sort arr in ascending order

In [5]:
print("Sorted Array : ",np.sort(arr))

Sorted Array :  [10 20 30 40 50]


🟢 Task 4: Ordering (Argsort)
---

Get the indices that would sort arr

In [6]:
print("Indices of That Array Are : ",np.argsort(arr))

Indices of That Array Are :  [0 1 2 3 4]


🟢 Task 5: Concatenation (1D)
---



Now move forward

Create:

    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])

Concatenate a and b into a single array

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("After Concatenate Array Look Like : ", np.concatenate([a,b]))

After Concatenate Array Look Like :  [1 2 3 4 5 6]


🟢 Task 6: Stacking (2D)
---

Using the same arrays a and b:

1.  Stack them vertically

2. Stack them horizontally

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertically Stack : \n", np.vstack((a,b)))
print("\n Horizontally Stack : \n", np.hstack((a,b)))

Vertically Stack : 
 [[1 2 3]
 [4 5 6]]

 Horizontally Stack : 
 [1 2 3 4 5 6]
