In [2]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

m = np.array([[1, 2, 3],
              [4, 5, 6]])


🟢 Task 1: Array Operations
---


Using a and b, perform and print:

1. Addition

2. Subtraction

3. Multiplication

Print each result.

In [11]:
print("Addition : ",a + b)
print("Subtraction : ",a - b)
print("Multiplication : ",a * b)

Addition :  [11 22 33]
Subtraction :  [ 9 18 27]
Multiplication :  [10 40 90]


🟢 Task 2: Broadcasting (Do this now)
---


 Add 10 to every element of array a


In [14]:
print("Add 10 to every element of array a\n",a + 10)

Add 10 to every element of array a
 [20 30 40]


🟢 Task 3: Row-wise Broadcasting
---

Add array a to matrix m.

Print the result.

In [13]:
print("Add array a to matrix m \n",a + m)

Add array a to matrix m 
 [[11 22 33]
 [14 25 36]]


🟢 Task 4: Aggregate Functions (Overall)
---



Using matrix m, print:

1. Sum of all elements

2. Mean of all elements

3. Maximum value

In [10]:
print("Sum of All Elements : ",np.sum(m))
print("Mean of All Elements : ",np.mean(m))
print("Maximum Value : ",np.max(m))

Sum of All Elements :  21
Mean of All Elements :  3.5
Maximum Value :  6


🟢 Task 5: Aggregate Functions (Axis-based)
---



 Using matrix m, print:

1. Sum across rows

2. Sum across columns

In [9]:
print("Sum of Rows : ", np.sum(m, axis=1))
print("Sum of Columns : ", np.sum(m, axis=0))

Sum of Rows :  [ 6 15]
Sum of Columns :  [5 7 9]
