In [2]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr)

[[10 20 30]
 [40 50 60]]


🟢 Task 1: Array Attributes
---



Using arr, print:

* shape

* ndim

* size

* dtype

In [3]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


🟢 Task 2: Indexing
---

From arr, extract:

* Element 50

* Entire first row

* Entire second column

 Print each result.

In [5]:
print(arr[1,1])
print(arr[0])
print(arr[:,1])

50
[10 20 30]
[20 50]


🟢 Task 3: Slicing
---



From arr, slice and print:

* Sub-array containing:

      20 30
      50 60

(Think rows + columns range)

In [6]:
print(arr[:,1:])

[[20 30]
 [50 60]]


🟢 Task 4: Boolean Indexing
---

Using arr, extract all elements greater than 30.

 Print the result.

In [8]:
print(arr[arr > 30])

[40 50 60]


🟢 Task 5: Reshaping
---


Reshape arr into a 1D array of length 6.

Print the reshaped array.

In [13]:
print(arr.reshape(6))

[1 2 3 4 5 6]


🟢 Task 6: Flattening
---

Flatten arr using any one flattening method.

Print the flattened array.

In [17]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr.flatten())

[10 20 30 40 50 60]
