🔹 Task 1: 1D Array (Basic)
---

Create a 1D NumPy array with these elements:
[2, 4, 6, 8, 10]

Print the array.

In [2]:
import numpy as np
arr = np.array([2, 4, 6, 8, 10])
print(arr)

[ 2  4  6  8 10]


🔹 Task 2: 2D Array (Manual)
---

Create a 2D array (2 rows, 3 columns)

Print the array.

In [14]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


🔹 Task 3: Zeros Array (2D)
---


Create a 2D NumPy array of zeros with:

*   3 rows
*   2 columns

Print the array.



In [21]:
import numpy as np
arr = np.zeros((3,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


🔹 Task 4: Ones Array (1D)
---


Create a 1D array of ones with length = 6

Print the array.





In [28]:
import numpy as np
arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


🔹 Task 5: Full Array (2D)
---

Create a 2D array of shape (2, 4)

Fill all values with 7

In [29]:
import numpy as np
arr = np.full((2,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]]


🔹 Task 6: Range-based 1D Array
---

 Create a 1D NumPy array:

*   Start = 5
*   End = 50
*   Step = 5






In [31]:
import numpy as np
arr = np.arange(5,51,5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


🔹 Task 7: Identity Matrix
---

Create a 4 × 4 identity matrix

Reminder:

* Identity matrix has 1 on the main diagonal

* Other values are 0

* Use NumPy’s built-in function

In [32]:
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
