### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [129]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)  # 1D

[1 2 3]


In [130]:
# 2D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [131]:
# 3D
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [132]:
# dtype
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [133]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
# with reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [135]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [136]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
# np.random
np.random.random((3,4))

array([[0.64615157, 0.6774924 , 0.59287384, 0.36686392],
       [0.53980056, 0.72238638, 0.13857967, 0.53974529],
       [0.47098432, 0.00637677, 0.12583402, 0.27076055]])

In [138]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [139]:
# np.identity
np.eye((4),dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Array Attributes

In [140]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [141]:
# ndim
a3.ndim

3

In [142]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [143]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [144]:
# itemsize
a3.itemsize

8

In [145]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [146]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [148]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [153]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [157]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [161]:
# vector operations
# arithmetic
print(a1,"\n")
print(a2,"\n")
print(a1 + a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


### Array Functions

In [165]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[37., 28., 69.],
       [75., 39., 12.],
       [39., 32., 69.]])

In [178]:
# max/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

# 0 -> col and 1 -> row
print("\n",a2)
print("Maximum value from each Row : ",np.max(a2,axis=1))
print("Maximum value from each Column : ",np.max(a2,axis=0))
print("Maximum value from each row : ", np.min(a2,axis=1))
print("Row Wise sum : ",np.sum(a2,axis=1))

75.0
12.0
400.0
216062620300800.0

 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Maximum value from each Row :  [15 19 23]
Maximum value from each Column :  [20 21 22 23]
Maximum value from each row :  [12 16 20]
Row Wise sum :  [54 70 86]


In [187]:
# mean/median/std/var
print(np.mean(a2,axis=0))  # Col. wise mean
print(np.median(a2,axis=1)) # row wise median
print(np.std(a2, axis = 1)) # row wise standard deviation
print(np.var(a2, axis = 0)) # col. wise variance

[16. 17. 18. 19.]
[13.5 17.5 21.5]
[1.11803399 1.11803399 1.11803399]
[10.66666667 10.66666667 10.66666667 10.66666667]


In [188]:
# trigonomoetric functions
np.sin(a2)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [189]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [193]:
# log and exponents
print(np.log(a1))
print("\n",np.exp(a1))

[[3.61091791 3.33220451 4.2341065 ]
 [4.31748811 3.66356165 2.48490665]
 [3.66356165 3.4657359  4.2341065 ]]

 [[1.17191424e+16 1.44625706e+12 9.25378173e+29]
 [3.73324200e+32 8.65934004e+16 1.62754791e+05]
 [8.65934004e+16 7.89629602e+13 9.25378173e+29]]


In [202]:
# round/floor/ceil
a = np.random.random((2,3))*100
print(a)
print("\nRound up : \n",np.round(a))
print("\nfloor : \n", np.floor(a))
print("\nceil : \n", np.ceil(a))

[[61.4340945  27.44319164 78.94217624]
 [ 8.18095788 29.34088568 51.41114934]]

Round up : 
 [[61. 27. 79.]
 [ 8. 29. 51.]]

floor : 
 [[61. 27. 78.]
 [ 8. 29. 51.]]

ceil : 
 [[62. 28. 79.]
 [ 9. 30. 52.]]


### Indexing and Slicing

In [203]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [204]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
a1[0]

np.int64(0)

In [206]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [210]:
a2[1,0]

np.int64(4)

In [211]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [212]:
a3[1,0,1]

np.int64(5)

In [213]:
a3[0,1,0]

np.int64(2)

In [214]:
a3[0,0,0]

np.int64(0)

In [215]:
a3[1,1,0]

np.int64(6)

In [216]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [217]:
a1[2:5:2]

array([2, 4])

In [218]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
a2[0,:]

array([0, 1, 2, 3])

In [223]:
a2[:,2]

array([ 2,  6, 10])

In [224]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [227]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [230]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [233]:
a2[1,::3]

array([4, 7])

In [234]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [236]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [239]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [240]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [246]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [250]:
a3[0,1,:]

array([3, 4, 5])

In [252]:
a3[1,:,1]

array([10, 13, 16])

In [253]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [257]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [261]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [259]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [262]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [260]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [263]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [264]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [267]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [268]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking


In [274]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [276]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [277]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [279]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [281]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [282]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]